spring.application.name=retailcore

spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/retailcore
spring.datasource.username=retailcore
spring.datasource.password=retailcore

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true